import 'package:flutter/widgets.dart';
import 'package:super_editor/src/infrastructure/actions.dart';

/// Stop propagating intents that prevent text input.
///
/// These intents have default handlers installed by Flutter
/// that prevents the key events from bubbling up to the IME.
///
/// Use this object in an [Actions] widget.
///
/// See [WidgetsApp.defaultShortcuts] for the list of keybindings that Flutter
/// adds by default.
final Map<Type, Action<Intent>> disabledWindowsIntents = {
  // Generated by pressing SPACE.
  // PrioritizedIntents might contain intents that we don't want to prevent
  // from bubbling up.
  // So, we need to look into its inner intents.
  PrioritizedIntents: PreventPrioritizedIntentsFromBubblingUp(
    intentFilter: (e) => e is ActivateIntent,
  ),
};
